image: php:7.0
pipelines:
    branches:
        master:
            - step:
                caches:
                    - node
                    - composer
                script:
                    # Install nvm
                    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && source ~/.nvm/nvm.sh
                    - nvm --version
                    # Install node 6
                    - nvm install 6 && nvm use 6
                    - node -v
                    # Install yarn
                    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.5
                    - export PATH=$HOME/.yarn/bin:$PATH
                    - yarn -V
                    # Install composer
                    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                    # Install dependencies
                    - docker-php-ext-install mysqli
                    - apt-get update && apt-get install -y unzip subversion gettext
                    - yarn
                    - composer install --no-interaction --no-progress --prefer-dist
                    # Setup test wordpress
                    - bash bin/install-wp-tests.sh wordpress_test test_user password 127.0.0.1 latest true
                    # Run scripts
                    - yarn run test
                    - yarn run build
                    - yarn run rmdist
                    - yarn run build:production
                    - composer test
                    - composer make-pot
                services:
                    - database
definitions:
    services:
        database:
            image: mysql
            environment:
                MYSQL_DATABASE: 'wordpress_test'
                MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
                MYSQL_USER: 'test_user'
                MYSQL_PASSWORD: 'password'
